#+TITLE:       Basic Magit Tutorial for Github
#+AUTHOR:      Mir Behroz Noor

- *Some Knowledge of Emacs*
- *Non-Expert Guidelines: Only for Personal Github*

*** Magit Push

1. Create/Select a repository on Github

2. Clone the Repo to your Local Computer ~M-x magit-clone~

3. Make your Changes or Add new files in Repo folder

4. In the Repo, press ~C-x g~ or in minibuffer ~M-x magit-status~

5. Check If there are untracked or unstaged changes from files, ~press s~ to stage desired or all files.

6. Better to split window before committing. It will automatically bring up the staged changes buffer and the committing buffer, easier to add comments.

7. Once the status changed to staged, add commit (comments), ~press c~ (x2)
   * In Commit Section: press ~C-c C-c~ to save and finish, or press ~C-c C-k~ to cancel

8. After committing, the ~M-x magit-status~ will show the commits in the ~Unmerged into x/y~

9. ~Press P~ to push changes then ~Press u~ to push main to upstream to the Github Repository.

10. Depending on option, it can either ask for the SSH passphrase or Github username and password.

10. Message in the minibuffer =Git finished=

11. The ~magit-status~ shows section ~Recent Commits~ at the top the last commit made to the repository in Github.
    ~Press Tab~ to unfold the list of all recent commits

*** Magit Pull [Trial and Error]

1. In the Repo, press ~C-x g~ or in minibuffer ~M-x magit-status~

2. If there are unstaged or uncommitted changes, ~M-x magit-reset-hard~

3. Once all cleared, go to the ~M-x magit-status~ buffer, press ~F~ either ~p~ or ~u~ to *pull into* main or master from *origin/master* or *origin/main*


*Learning Emacs*

#+begin_quote
"There is no end, my friend"
David Goggins
#+end_quote
